name: zoc_lms_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.6.6
  awesome_bottom_bar: ^1.2.4
  shared_preferences: ^2.1.0
  # url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  carousel_slider: ^5.0.0
  flutter_spinkit: ^5.2.1
  flutter_inappwebview: ^6.1.5
  http: ^1.2.2
  flutter_staggered_grid_view: ^0.7.0
  youtube_player_flutter: ^9.1.1
  vs_scrollbar: ^1.0.0
  lottie: ^3.1.3
  url_launcher: ^6.3.1
  # sqflite: ^2.4.1
  # flutter_web_browser: ^0.17.1
  # url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/

